### PR TITLE
good practices for rmarkdown

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Something I noticed while going through TLF-library's vignettes and a similar pattern is present across package vignettes in the ecosystem, so thought I would add a section on a few rmarkdown good practices. I will keep updating this section as I encounter other issues.

**Comment by PavelBal** [comment]
Awsome.

**Comment by IndrajeetPatil** [comment]
@msevestre This PR is ready for review!

**Comment by msevestre** [comment]
Looking great

**Pull request merged**
