### PR TITLE
Version 11.1

### PR DESCRIPTION
**Pull request by Yuri05**
Can be merged after the Release Notes and all remaining TODOs (e.g. ospsuite-R release) are finalized

### CODE REVIEW

**Comment by Yuri05** [comment]
TODOs before merge and finally publishing the release:
- [ ] Set [ospsuite.utils](https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/releases/tag/v1.4.23) pre-release ▶️ release
- [ ] Set [TLF](https://github.com/Open-Systems-Pharmacology/TLF-Library/releases/tag/v1.5.121) pre-release ▶️ release
- [ ] Set [ospsuite-R](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/releases/tag/v11.1.197) pre-release ▶️ release
- [ ] Set [OSP-PBPK-Model-Library](https://github.com/Open-Systems-Pharmacology/OSP-PBPK-Model-Library/releases/tag/v11.1) pre-release ▶️ release
- [ ] Set [OSP-Qualification-Reports](https://github.com/Open-Systems-Pharmacology/OSP-Qualification-Reports/releases/tag/v11.1) pre-release ▶️ release
- [ ] Set [Qualification Runner](https://github.com/Open-Systems-Pharmacology/QualificationRunner/releases/tag/v11.1) pre-release ▶️ release

@msevestre Anything else?

**Comment by msevestre** [comment]
What's with the qualification runner? Why is it different than all other projects?

We need to publish the nuget packages

**Comment by Yuri05** [comment]
>What's with the qualification runner? Why is it different than all other projects?

What do you mean?

**Comment by msevestre** [comment]
Well PKSim,MoBi, etc...what makes qualificationrunner so Special in this list?

**Comment by Yuri05** [comment]
Qualification Runner is installed by the end users (as part of qualification framework)
PK-Sim etc. usually only with the Suite, not standalone

**Comment by Yuri05** [comment]
@msevestre ready to review and merge

**Comment by msevestre** [comment]
@Yuri05 Ok I am going to do it :)

**Review by msevestre — APPROVED** [review]

**Pull request merged**
